// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	model "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/adapters/repository/file/audit/model"
	dto "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/application/dto"
)

type AuditConverterImpl struct{}

func (c *AuditConverterImpl) ToModel(source dto.AuditEvent) model.AuditEvent {
	var modelAuditEvent model.AuditEvent
	modelAuditEvent.TS = source.TS
	if source.Metrics != nil {
		modelAuditEvent.Metrics = make([]string, len(source.Metrics))
		for i := 0; i < len(source.Metrics); i++ {
			modelAuditEvent.Metrics[i] = source.Metrics[i]
		}
	}
	modelAuditEvent.IPAddress = source.IPAddress
	return modelAuditEvent
}
