// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	model "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/adapters/repository/file/metrics/model"
	entity "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/domain/entity"
)

type MetricConverterImpl struct{}

func (c *MetricConverterImpl) ToEntity(source model.Metric) entity.Metric {
	var entityMetric entity.Metric
	entityMetric.ID = source.ID
	entityMetric.MType = entity.MetricType(source.MType)
	if source.Delta != nil {
		xint64 := *source.Delta
		entityMetric.Delta = &xint64
	}
	if source.Value != nil {
		xfloat64 := *source.Value
		entityMetric.Value = &xfloat64
	}
	entityMetric.Hash = source.Hash
	return entityMetric
}
func (c *MetricConverterImpl) ToModel(source entity.Metric) model.Metric {
	var modelMetric model.Metric
	modelMetric.ID = source.ID
	modelMetric.MType = string(source.MType)
	if source.Delta != nil {
		xint64 := *source.Delta
		modelMetric.Delta = &xint64
	}
	if source.Value != nil {
		xfloat64 := *source.Value
		modelMetric.Value = &xfloat64
	}
	modelMetric.Hash = source.Hash
	return modelMetric
}
