// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/collector/application/port/metrics_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/collector/application/port/metrics_repository.go -destination=internal/agent/collector/application/port/mocks/mock_metrics_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	runtime "runtime"

	entity "github.com/iPatrushevSergey/metrics/app/internal/agent/collector/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRepository is a mock of MetricsRepository interface.
type MockMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricsRepositoryMockRecorder is the mock recorder for MockMetricsRepository.
type MockMetricsRepositoryMockRecorder struct {
	mock *MockMetricsRepository
}

// NewMockMetricsRepository creates a new mock instance.
func NewMockMetricsRepository(ctrl *gomock.Controller) *MockMetricsRepository {
	mock := &MockMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRepository) EXPECT() *MockMetricsRepositoryMockRecorder {
	return m.recorder
}

// GetSystemMetrics mocks base method.
func (m *MockMetricsRepository) GetSystemMetrics() entity.SystemMetrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemMetrics")
	ret0, _ := ret[0].(entity.SystemMetrics)
	return ret0
}

// GetSystemMetrics indicates an expected call of GetSystemMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetSystemMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetSystemMetrics))
}

// UpdateGopsutilMetrics mocks base method.
func (m *MockMetricsRepository) UpdateGopsutilMetrics(totalMem, freeMem float64, cpu []float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateGopsutilMetrics", totalMem, freeMem, cpu)
}

// UpdateGopsutilMetrics indicates an expected call of UpdateGopsutilMetrics.
func (mr *MockMetricsRepositoryMockRecorder) UpdateGopsutilMetrics(totalMem, freeMem, cpu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGopsutilMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).UpdateGopsutilMetrics), totalMem, freeMem, cpu)
}

// UpdateRuntimeMetrics mocks base method.
func (m *MockMetricsRepository) UpdateRuntimeMetrics(ms runtime.MemStats, randValue float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateRuntimeMetrics", ms, randValue)
}

// UpdateRuntimeMetrics indicates an expected call of UpdateRuntimeMetrics.
func (mr *MockMetricsRepositoryMockRecorder) UpdateRuntimeMetrics(ms, randValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRuntimeMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).UpdateRuntimeMetrics), ms, randValue)
}
