// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/collector/application/port/metrics_sampler.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/collector/application/port/metrics_sampler.go -destination=internal/agent/collector/application/port/mocks/mock_metrics_sampler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	runtime "runtime"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsSampler is a mock of MetricsSampler interface.
type MockMetricsSampler struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsSamplerMockRecorder
	isgomock struct{}
}

// MockMetricsSamplerMockRecorder is the mock recorder for MockMetricsSampler.
type MockMetricsSamplerMockRecorder struct {
	mock *MockMetricsSampler
}

// NewMockMetricsSampler creates a new mock instance.
func NewMockMetricsSampler(ctrl *gomock.Controller) *MockMetricsSampler {
	mock := &MockMetricsSampler{ctrl: ctrl}
	mock.recorder = &MockMetricsSamplerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsSampler) EXPECT() *MockMetricsSamplerMockRecorder {
	return m.recorder
}

// ReadCPUPercent mocks base method.
func (m *MockMetricsSampler) ReadCPUPercent(interval time.Duration, perCPU bool) ([]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCPUPercent", interval, perCPU)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCPUPercent indicates an expected call of ReadCPUPercent.
func (mr *MockMetricsSamplerMockRecorder) ReadCPUPercent(interval, perCPU any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCPUPercent", reflect.TypeOf((*MockMetricsSampler)(nil).ReadCPUPercent), interval, perCPU)
}

// ReadMemStats mocks base method.
func (m *MockMetricsSampler) ReadMemStats() runtime.MemStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMemStats")
	ret0, _ := ret[0].(runtime.MemStats)
	return ret0
}

// ReadMemStats indicates an expected call of ReadMemStats.
func (mr *MockMetricsSamplerMockRecorder) ReadMemStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMemStats", reflect.TypeOf((*MockMetricsSampler)(nil).ReadMemStats))
}

// ReadVirtualMemory mocks base method.
func (m *MockMetricsSampler) ReadVirtualMemory() (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadVirtualMemory")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadVirtualMemory indicates an expected call of ReadVirtualMemory.
func (mr *MockMetricsSamplerMockRecorder) ReadVirtualMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadVirtualMemory", reflect.TypeOf((*MockMetricsSampler)(nil).ReadVirtualMemory))
}
