// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/collector/application/port/metrics_gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/collector/application/port/metrics_gateway.go -destination=internal/agent/collector/application/port/mocks/mock_metrics_gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/iPatrushevSergey/metrics/app/internal/agent/collector/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsGateway is a mock of MetricsGateway interface.
type MockMetricsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsGatewayMockRecorder
	isgomock struct{}
}

// MockMetricsGatewayMockRecorder is the mock recorder for MockMetricsGateway.
type MockMetricsGatewayMockRecorder struct {
	mock *MockMetricsGateway
}

// NewMockMetricsGateway creates a new mock instance.
func NewMockMetricsGateway(ctrl *gomock.Controller) *MockMetricsGateway {
	mock := &MockMetricsGateway{ctrl: ctrl}
	mock.recorder = &MockMetricsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsGateway) EXPECT() *MockMetricsGatewayMockRecorder {
	return m.recorder
}

// MetricsUpdateBatch mocks base method.
func (m *MockMetricsGateway) MetricsUpdateBatch(ctx context.Context, metrics []dto.MetricUpdateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricsUpdateBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// MetricsUpdateBatch indicates an expected call of MetricsUpdateBatch.
func (mr *MockMetricsGatewayMockRecorder) MetricsUpdateBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricsUpdateBatch", reflect.TypeOf((*MockMetricsGateway)(nil).MetricsUpdateBatch), ctx, metrics)
}
