package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// resetDirective is the marker substring matched in documentation comments.
const resetDirective = "generate:reset"

func main() {
	root := flag.String("root", ".", "module or subtree root: packages.Load runs as from this directory with pattern ./...")
	flag.Parse()

	if err := run(*root); err != nil {
		fmt.Fprintf(os.Stderr, "reset: %v\n", err)
		os.Exit(1)
	}
}

// run loads all packages under abs(root), generates reset.gen.go where needed.
func run(root string) error {
	abs, err := filepath.Abs(root)
	if err != nil {
		return err
	}

	pkgs, err := loadPackages(abs)
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {
		if skipPackage(abs, pkg) {
			continue
		}
		reportPackageErrors(pkg)
		if err := processPackage(pkg); err != nil {
			return err
		}
	}
	return nil
}

// loadPackages is equivalent to go list ./... from root with syntax and type info.
func loadPackages(root string) ([]*packages.Package, error) {
	fset := token.NewFileSet()
	cfg := &packages.Config{
		Fset: fset,
		Dir:  root,
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedImports,
	}
	return packages.Load(cfg, "./...")
}

// skipPackage skips pkg if its path relative to root contains a blocked segment.
func skipPackage(root string, pkg *packages.Package) bool {
	rel, err := filepath.Rel(root, pkg.Dir)
	if err != nil {
		return false
	}
	rel = filepath.ToSlash(rel)
	for _, seg := range strings.Split(rel, "/") {
		if skipPathSegment(seg) {
			return true
		}
	}
	return false
}

func skipPathSegment(name string) bool {
	// Hidden directories: .git, .github, etc.
	switch name {
	case "profiles", "pkg", "migrations", "api":
		return true
	}
	return len(name) > 1 && name[0] == '.'
}

func reportPackageErrors(pkg *packages.Package) {
	// Load/typecheck issues: still attempt generation when syntax is present.
	for _, e := range pkg.Errors {
		fmt.Fprintf(os.Stderr, "%s: %v\n", pkg.PkgPath, e)
	}
}

type resetTarget struct {
	name string
	spec *ast.TypeSpec // named struct type with // generate:reset
}

func processPackage(pkg *packages.Package) error {
	var targets []resetTarget
	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Type == nil {
					continue
				}
				if _, ok := ts.Type.(*ast.StructType); !ok {
					continue
				}
				if !hasResetDirective(gd.Doc, ts.Doc) {
					continue
				}
				targets = append(targets, resetTarget{name: ts.Name.Name, spec: ts})
			}
		}
	}
	if len(targets) == 0 {
		return nil
	}

	sort.Slice(targets, func(i, j int) bool { return targets[i].name < targets[j].name })

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

	for _, t := range targets {
		obj := pkg.TypesInfo.Defs[t.spec.Name]
		if obj == nil {
			return fmt.Errorf("%s: no TypesInfo for type %s", pkg.PkgPath, t.name)
		}
		tn, ok := obj.(*types.TypeName)
		if !ok {
			return fmt.Errorf("%s: %s is not a TypeName", pkg.PkgPath, t.name)
		}
		named := tn.Type().(*types.Named)
		st, ok := named.Underlying().(*types.Struct)
		if !ok {
			return fmt.Errorf("%s: %s underlying is not a struct", pkg.PkgPath, t.name)
		}
		method, err := genResetMethod("v", named, st)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", pkg.PkgPath, t.name, err)
		}
		buf.WriteString(method)
		buf.WriteByte('\n')
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w\n---\n%s", err, buf.String())
	}

	path := filepath.Join(pkg.Dir, "reset.gen.go")
	return os.WriteFile(path, out, 0644)
}

// genResetMethod emits the Reset method for named struct.
func genResetMethod(recv string, named *types.Named, st *types.Struct) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "func (%s *%s) Reset() {\n", recv, named.Obj().Name())
	fmt.Fprintf(&b, "if %s == nil {\nreturn\n}\n", recv)
	lines, err := resetStructFields(recv, st)
	if err != nil {
		return "", err
	}
	for _, line := range lines {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// resetStructFields produces assignment lines for each field of st accessed via recv.
func resetStructFields(recv string, st *types.Struct) ([]string, error) {
	var out []string
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		expr := recv + "." + f.Name()
		lines, err := resetExpr(expr, f.Type())
		if err != nil {
			return nil, fmt.Errorf("field %s: %w", f.Name(), err)
		}
		out = append(out, lines...)
	}
	return out, nil
}

// resetExpr returns Go source lines that reset expr to zero value for typ.
func resetExpr(expr string, typ types.Type) ([]string, error) {
	typ = types.Unalias(typ)
	if ptr, ok := typ.(*types.Pointer); ok {
		return resetPointer(expr, ptr)
	}

	switch t := typ.Underlying().(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("%s = %s", expr, zeroLiteral(t))}, nil
	case *types.Slice:
		return []string{fmt.Sprintf("%s = %s[:0]", expr, expr)}, nil
	case *types.Map:
		return []string{fmt.Sprintf("clear(%s)", expr)}, nil
	case *types.Struct:
		var named *types.Named
		if n, ok := typ.(*types.Named); ok {
			named = n
		}
		return resetStructValue(expr, t, named)
	case *types.Interface:
		if t.NumMethods() == 0 {
			return resetEmptyInterface(expr), nil
		}
		return nil, fmt.Errorf("non-empty interface not supported: %s", expr)
	default:
		return nil, fmt.Errorf("unsupported type: %s", typ)
	}
}

func resetStructValue(expr string, st *types.Struct, named *types.Named) ([]string, error) {
	// named is nil for anonymous struct literals only.
	if named != nil && hasResetMethod(named) {
		return []string{fmt.Sprintf("%s.Reset()", expr)}, nil
	}
	var out []string
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		sub := expr + "." + f.Name()
		lines, err := resetExpr(sub, f.Type())
		if err != nil {
			return nil, err
		}
		out = append(out, lines...)
	}
	return out, nil
}

func resetPointer(expr string, ptr *types.Pointer) ([]string, error) {
	// expr has type *elem.
	elem := types.Unalias(ptr.Elem())
	switch u := elem.Underlying().(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("if %s != nil { *%s = %s }", expr, expr, zeroLiteral(u))}, nil
	case *types.Slice:
		return []string{fmt.Sprintf("if %s != nil { *%s = (*%s)[:0] }", expr, expr, expr)}, nil
	case *types.Map:
		return []string{fmt.Sprintf("if %s != nil { clear(*%s) }", expr, expr)}, nil
	case *types.Pointer:
		inner := resetPointerDeref(expr, elem.(*types.Pointer))
		return inner, nil
	case *types.Struct:
		var named *types.Named
		if n, ok := elem.(*types.Named); ok {
			named = n
		}
		return resetPointerToStruct(expr, u, named)
	default:
		if named, ok := elem.(*types.Named); ok {
			if st, ok := named.Underlying().(*types.Struct); ok {
				return resetPointerToStruct(expr, st, named)
			}
		}
		return nil, fmt.Errorf("unsupported pointer element type: %s", elem)
	}
}

// resetPointerDeref handles **T (double pointer): basic or outer set to nil.
func resetPointerDeref(ptrExpr string, inner *types.Pointer) []string {
	elem := types.Unalias(inner.Elem())
	if b, ok := elem.Underlying().(*types.Basic); ok {
		return []string{fmt.Sprintf("if %s != nil && *%s != nil { **%s = %s }", ptrExpr, ptrExpr, ptrExpr, zeroLiteral(b))}
	}
	return []string{fmt.Sprintf("if %s != nil { *%s = nil }", ptrExpr, ptrExpr)}
}

func resetPointerToStruct(expr string, st *types.Struct, named *types.Named) ([]string, error) {
	// expr is *struct; named may be nil for anonymous struct.
	if named != nil && hasResetMethod(named) {
		return []string{fmt.Sprintf("if %s != nil { %s.Reset() }", expr, expr)}, nil
	}
	recv := "(*" + expr + ")"
	inner, err := resetStructFields(recv, st)
	if err != nil {
		return nil, err
	}
	out := []string{fmt.Sprintf("if %s != nil {", expr)}
	for _, l := range inner {
		out = append(out, l)
	}
	out = append(out, "}")
	return out, nil
}

func resetEmptyInterface(expr string) []string {
	// interface{} only; calls Reset if implemented.
	return []string{
		fmt.Sprintf("if resetter, ok := %s.(interface{ Reset() }); ok {", expr),
		"\tresetter.Reset()",
		"}",
	}
}

// hasResetMethod reports whether *named has func Reset() with no params/results.
func hasResetMethod(named *types.Named) bool {
	ms := types.NewMethodSet(types.NewPointer(named))
	for i := 0; i < ms.Len(); i++ {
		sel := ms.At(i)
		if sel.Obj().Name() != "Reset" {
			continue
		}
		fn, ok := sel.Obj().(*types.Func)
		if !ok {
			continue
		}
		sig := fn.Type().(*types.Signature)
		if sig.Params().Len() == 0 && sig.Results().Len() == 0 {
			return true
		}
	}
	return false
}

func zeroLiteral(b *types.Basic) string {
	// Source text for the zero value of a basic kind.
	switch b.Kind() {
	case types.String:
		return `""`
	case types.Bool:
		return "false"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr:
		return "0"
	case types.Float32, types.Float64:
		return "0"
	case types.Complex64, types.Complex128:
		return "0"
	case types.UnsafePointer:
		return "nil"
	default:
		return "0"
	}
}

func hasResetDirective(genDoc, typeDoc *ast.CommentGroup) bool {
	if containsDirective(genDoc) {
		return true
	}
	return containsDirective(typeDoc)
}

func containsDirective(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if strings.Contains(line, resetDirective) {
			return true
		}
	}
	return false
}
