// Code generated by cmd/reset; DO NOT EDIT.

package fixture

func (v *AllCases) Reset() {
	if v == nil {
		return
	}
	v.UserName = ""
	v.RequestCount = 0
	v.IsEnabled = false
	v.RawByte = 0
	v.UnicodeRune = 0
	v.AverageScore32 = 0
	v.AverageScore64 = 0
	v.AliasName = ""
	v.IDsByOrder = v.IDsByOrder[:0]
	clear(v.ScoreByKey)
	v.Address.ZipCode = 0
	v.Session.Reset()
	v.addressData.ZipCode = 0
	if v.OptionalCount != nil {
		*v.OptionalCount = 0
	}
	if v.OptionalTags != nil {
		*v.OptionalTags = (*v.OptionalTags)[:0]
	}
	if v.OptionalCodeToName != nil {
		clear(*v.OptionalCodeToName)
	}
	if v.OptionalAddress != nil {
		(*v.OptionalAddress).ZipCode = 0
	}
	if v.OptionalSession != nil {
		v.OptionalSession.Reset()
	}
	if v.OptionalPtrCount != nil && *v.OptionalPtrCount != nil {
		**v.OptionalPtrCount = 0
	}
	if resetter, ok := v.Payload.(interface{ Reset() }); ok {
		resetter.Reset()
	}
}
