// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	model "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/adapters/repository/postgres/model"
	entity "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/domain/entity"
)

type MetricConverterImpl struct{}

func (c *MetricConverterImpl) ToEntity(source model.Metric) entity.Metric {
	var entityMetric entity.Metric
	entityMetric.ID = source.ID
	entityMetric.MType = entity.MetricType(source.MType)
	entityMetric.Delta = source.Delta
	entityMetric.Value = source.Value
	if source.Hash != nil {
		entityMetric.Hash = *source.Hash
	}
	return entityMetric
}

func (c *MetricConverterImpl) ToModel(source entity.Metric) model.Metric {
	var modelMetric model.Metric
	modelMetric.ID = source.ID
	modelMetric.MType = string(source.MType)
	modelMetric.Delta = source.Delta
	modelMetric.Value = source.Value
	if source.Hash != "" {
		h := source.Hash
		modelMetric.Hash = &h
	}
	return modelMetric
}
