// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/metrics/application/port/metrics_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/metrics/application/port/metrics_repository.go -destination=internal/server/metrics/application/port/mocks/mock_metrics_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricReader is a mock of MetricReader interface.
type MockMetricReader struct {
	ctrl     *gomock.Controller
	recorder *MockMetricReaderMockRecorder
	isgomock struct{}
}

// MockMetricReaderMockRecorder is the mock recorder for MockMetricReader.
type MockMetricReaderMockRecorder struct {
	mock *MockMetricReader
}

// NewMockMetricReader creates a new mock instance.
func NewMockMetricReader(ctrl *gomock.Controller) *MockMetricReader {
	mock := &MockMetricReader{ctrl: ctrl}
	mock.recorder = &MockMetricReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricReader) EXPECT() *MockMetricReaderMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockMetricReader) GetAll(ctx context.Context) (map[string]entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(map[string]entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMetricReaderMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMetricReader)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockMetricReader) GetByID(ctx context.Context, id string) (entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMetricReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMetricReader)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockMetricReader) GetByIDs(ctx context.Context, ids []string) (map[string]entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].(map[string]entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockMetricReaderMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockMetricReader)(nil).GetByIDs), ctx, ids)
}

// Ping mocks base method.
func (m *MockMetricReader) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMetricReaderMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMetricReader)(nil).Ping), ctx)
}

// MockMetricWriter is a mock of MetricWriter interface.
type MockMetricWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricWriterMockRecorder
	isgomock struct{}
}

// MockMetricWriterMockRecorder is the mock recorder for MockMetricWriter.
type MockMetricWriterMockRecorder struct {
	mock *MockMetricWriter
}

// NewMockMetricWriter creates a new mock instance.
func NewMockMetricWriter(ctrl *gomock.Controller) *MockMetricWriter {
	mock := &MockMetricWriter{ctrl: ctrl}
	mock.recorder = &MockMetricWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricWriter) EXPECT() *MockMetricWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMetricWriter) Create(ctx context.Context, metric entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMetricWriterMockRecorder) Create(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMetricWriter)(nil).Create), ctx, metric)
}

// CreateBatchWithCopy mocks base method.
func (m *MockMetricWriter) CreateBatchWithCopy(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithCopy", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithCopy indicates an expected call of CreateBatchWithCopy.
func (mr *MockMetricWriterMockRecorder) CreateBatchWithCopy(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithCopy", reflect.TypeOf((*MockMetricWriter)(nil).CreateBatchWithCopy), ctx, metrics)
}

// CreateBatchWithParams mocks base method.
func (m *MockMetricWriter) CreateBatchWithParams(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithParams", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithParams indicates an expected call of CreateBatchWithParams.
func (mr *MockMetricWriterMockRecorder) CreateBatchWithParams(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithParams", reflect.TypeOf((*MockMetricWriter)(nil).CreateBatchWithParams), ctx, metrics)
}

// CreateBatchWithPrepare mocks base method.
func (m *MockMetricWriter) CreateBatchWithPrepare(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithPrepare", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithPrepare indicates an expected call of CreateBatchWithPrepare.
func (mr *MockMetricWriterMockRecorder) CreateBatchWithPrepare(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithPrepare", reflect.TypeOf((*MockMetricWriter)(nil).CreateBatchWithPrepare), ctx, metrics)
}

// CreateBatchWithUnnest mocks base method.
func (m *MockMetricWriter) CreateBatchWithUnnest(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithUnnest", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithUnnest indicates an expected call of CreateBatchWithUnnest.
func (mr *MockMetricWriterMockRecorder) CreateBatchWithUnnest(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithUnnest", reflect.TypeOf((*MockMetricWriter)(nil).CreateBatchWithUnnest), ctx, metrics)
}

// Update mocks base method.
func (m *MockMetricWriter) Update(ctx context.Context, metric entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricWriterMockRecorder) Update(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricWriter)(nil).Update), ctx, metric)
}

// UpdateBatchWithCopy mocks base method.
func (m *MockMetricWriter) UpdateBatchWithCopy(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithCopy", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithCopy indicates an expected call of UpdateBatchWithCopy.
func (mr *MockMetricWriterMockRecorder) UpdateBatchWithCopy(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithCopy", reflect.TypeOf((*MockMetricWriter)(nil).UpdateBatchWithCopy), ctx, metrics)
}

// UpdateBatchWithParams mocks base method.
func (m *MockMetricWriter) UpdateBatchWithParams(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithParams", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithParams indicates an expected call of UpdateBatchWithParams.
func (mr *MockMetricWriterMockRecorder) UpdateBatchWithParams(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithParams", reflect.TypeOf((*MockMetricWriter)(nil).UpdateBatchWithParams), ctx, metrics)
}

// UpdateBatchWithPrepare mocks base method.
func (m *MockMetricWriter) UpdateBatchWithPrepare(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithPrepare", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithPrepare indicates an expected call of UpdateBatchWithPrepare.
func (mr *MockMetricWriterMockRecorder) UpdateBatchWithPrepare(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithPrepare", reflect.TypeOf((*MockMetricWriter)(nil).UpdateBatchWithPrepare), ctx, metrics)
}

// UpdateBatchWithUnnest mocks base method.
func (m *MockMetricWriter) UpdateBatchWithUnnest(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithUnnest", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithUnnest indicates an expected call of UpdateBatchWithUnnest.
func (mr *MockMetricWriterMockRecorder) UpdateBatchWithUnnest(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithUnnest", reflect.TypeOf((*MockMetricWriter)(nil).UpdateBatchWithUnnest), ctx, metrics)
}

// MockMetricRepository is a mock of MetricRepository interface.
type MockMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricRepositoryMockRecorder is the mock recorder for MockMetricRepository.
type MockMetricRepositoryMockRecorder struct {
	mock *MockMetricRepository
}

// NewMockMetricRepository creates a new mock instance.
func NewMockMetricRepository(ctrl *gomock.Controller) *MockMetricRepository {
	mock := &MockMetricRepository{ctrl: ctrl}
	mock.recorder = &MockMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricRepository) EXPECT() *MockMetricRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMetricRepository) Create(ctx context.Context, metric entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMetricRepositoryMockRecorder) Create(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMetricRepository)(nil).Create), ctx, metric)
}

// CreateBatchWithCopy mocks base method.
func (m *MockMetricRepository) CreateBatchWithCopy(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithCopy", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithCopy indicates an expected call of CreateBatchWithCopy.
func (mr *MockMetricRepositoryMockRecorder) CreateBatchWithCopy(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithCopy", reflect.TypeOf((*MockMetricRepository)(nil).CreateBatchWithCopy), ctx, metrics)
}

// CreateBatchWithParams mocks base method.
func (m *MockMetricRepository) CreateBatchWithParams(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithParams", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithParams indicates an expected call of CreateBatchWithParams.
func (mr *MockMetricRepositoryMockRecorder) CreateBatchWithParams(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithParams", reflect.TypeOf((*MockMetricRepository)(nil).CreateBatchWithParams), ctx, metrics)
}

// CreateBatchWithPrepare mocks base method.
func (m *MockMetricRepository) CreateBatchWithPrepare(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithPrepare", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithPrepare indicates an expected call of CreateBatchWithPrepare.
func (mr *MockMetricRepositoryMockRecorder) CreateBatchWithPrepare(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithPrepare", reflect.TypeOf((*MockMetricRepository)(nil).CreateBatchWithPrepare), ctx, metrics)
}

// CreateBatchWithUnnest mocks base method.
func (m *MockMetricRepository) CreateBatchWithUnnest(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithUnnest", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithUnnest indicates an expected call of CreateBatchWithUnnest.
func (mr *MockMetricRepositoryMockRecorder) CreateBatchWithUnnest(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithUnnest", reflect.TypeOf((*MockMetricRepository)(nil).CreateBatchWithUnnest), ctx, metrics)
}

// GetAll mocks base method.
func (m *MockMetricRepository) GetAll(ctx context.Context) (map[string]entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(map[string]entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMetricRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMetricRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockMetricRepository) GetByID(ctx context.Context, id string) (entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMetricRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMetricRepository)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockMetricRepository) GetByIDs(ctx context.Context, ids []string) (map[string]entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].(map[string]entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockMetricRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockMetricRepository)(nil).GetByIDs), ctx, ids)
}

// Ping mocks base method.
func (m *MockMetricRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMetricRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMetricRepository)(nil).Ping), ctx)
}

// Update mocks base method.
func (m *MockMetricRepository) Update(ctx context.Context, metric entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricRepositoryMockRecorder) Update(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricRepository)(nil).Update), ctx, metric)
}

// UpdateBatchWithCopy mocks base method.
func (m *MockMetricRepository) UpdateBatchWithCopy(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithCopy", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithCopy indicates an expected call of UpdateBatchWithCopy.
func (mr *MockMetricRepositoryMockRecorder) UpdateBatchWithCopy(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithCopy", reflect.TypeOf((*MockMetricRepository)(nil).UpdateBatchWithCopy), ctx, metrics)
}

// UpdateBatchWithParams mocks base method.
func (m *MockMetricRepository) UpdateBatchWithParams(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithParams", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithParams indicates an expected call of UpdateBatchWithParams.
func (mr *MockMetricRepositoryMockRecorder) UpdateBatchWithParams(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithParams", reflect.TypeOf((*MockMetricRepository)(nil).UpdateBatchWithParams), ctx, metrics)
}

// UpdateBatchWithPrepare mocks base method.
func (m *MockMetricRepository) UpdateBatchWithPrepare(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithPrepare", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithPrepare indicates an expected call of UpdateBatchWithPrepare.
func (mr *MockMetricRepositoryMockRecorder) UpdateBatchWithPrepare(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithPrepare", reflect.TypeOf((*MockMetricRepository)(nil).UpdateBatchWithPrepare), ctx, metrics)
}

// UpdateBatchWithUnnest mocks base method.
func (m *MockMetricRepository) UpdateBatchWithUnnest(ctx context.Context, metrics []entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatchWithUnnest", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatchWithUnnest indicates an expected call of UpdateBatchWithUnnest.
func (mr *MockMetricRepositoryMockRecorder) UpdateBatchWithUnnest(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatchWithUnnest", reflect.TypeOf((*MockMetricRepository)(nil).UpdateBatchWithUnnest), ctx, metrics)
}
