// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/metrics/application/port/audit_file_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/metrics/application/port/audit_file_repository.go -destination=internal/server/metrics/application/port/mocks/mock_audit_file_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditFileRepository is a mock of AuditFileRepository interface.
type MockAuditFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditFileRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditFileRepositoryMockRecorder is the mock recorder for MockAuditFileRepository.
type MockAuditFileRepositoryMockRecorder struct {
	mock *MockAuditFileRepository
}

// NewMockAuditFileRepository creates a new mock instance.
func NewMockAuditFileRepository(ctrl *gomock.Controller) *MockAuditFileRepository {
	mock := &MockAuditFileRepository{ctrl: ctrl}
	mock.recorder = &MockAuditFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditFileRepository) EXPECT() *MockAuditFileRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockAuditFileRepository) Append(ctx context.Context, e dto.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockAuditFileRepositoryMockRecorder) Append(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockAuditFileRepository)(nil).Append), ctx, e)
}

// Close mocks base method.
func (m *MockAuditFileRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAuditFileRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAuditFileRepository)(nil).Close))
}
