// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/metrics/application/port/metric_file_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/metrics/application/port/metric_file_repository.go -destination=internal/server/metrics/application/port/mocks/mock_metric_file_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricFileRepository is a mock of MetricFileRepository interface.
type MockMetricFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricFileRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricFileRepositoryMockRecorder is the mock recorder for MockMetricFileRepository.
type MockMetricFileRepositoryMockRecorder struct {
	mock *MockMetricFileRepository
}

// NewMockMetricFileRepository creates a new mock instance.
func NewMockMetricFileRepository(ctrl *gomock.Controller) *MockMetricFileRepository {
	mock := &MockMetricFileRepository{ctrl: ctrl}
	mock.recorder = &MockMetricFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricFileRepository) EXPECT() *MockMetricFileRepositoryMockRecorder {
	return m.recorder
}

// LoadAll mocks base method.
func (m *MockMetricFileRepository) LoadAll(ctx context.Context) ([]entity.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll", ctx)
	ret0, _ := ret[0].([]entity.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockMetricFileRepositoryMockRecorder) LoadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockMetricFileRepository)(nil).LoadAll), ctx)
}

// SaveAll mocks base method.
func (m *MockMetricFileRepository) SaveAll(ctx context.Context, metrics map[string]entity.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockMetricFileRepositoryMockRecorder) SaveAll(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockMetricFileRepository)(nil).SaveAll), ctx, metrics)
}
