// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/metrics/application/port/audit_gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/metrics/application/port/audit_gateway.go -destination=internal/server/metrics/application/port/mocks/mock_audit_gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditGateway is a mock of AuditGateway interface.
type MockAuditGateway struct {
	ctrl     *gomock.Controller
	recorder *MockAuditGatewayMockRecorder
	isgomock struct{}
}

// MockAuditGatewayMockRecorder is the mock recorder for MockAuditGateway.
type MockAuditGatewayMockRecorder struct {
	mock *MockAuditGateway
}

// NewMockAuditGateway creates a new mock instance.
func NewMockAuditGateway(ctrl *gomock.Controller) *MockAuditGateway {
	mock := &MockAuditGateway{ctrl: ctrl}
	mock.recorder = &MockAuditGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditGateway) EXPECT() *MockAuditGatewayMockRecorder {
	return m.recorder
}

// CreateAudit mocks base method.
func (m *MockAuditGateway) CreateAudit(ctx context.Context, e dto.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAudit", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAudit indicates an expected call of CreateAudit.
func (mr *MockAuditGatewayMockRecorder) CreateAudit(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAudit", reflect.TypeOf((*MockAuditGateway)(nil).CreateAudit), ctx, e)
}
