// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/metrics/application/port/audit_publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/metrics/application/port/audit_publisher.go -destination=internal/server/metrics/application/port/mocks/mock_audit_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/iPatrushevSergey/metrics/app/internal/server/metrics/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditPublisher is a mock of AuditPublisher interface.
type MockAuditPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherMockRecorder
	isgomock struct{}
}

// MockAuditPublisherMockRecorder is the mock recorder for MockAuditPublisher.
type MockAuditPublisherMockRecorder struct {
	mock *MockAuditPublisher
}

// NewMockAuditPublisher creates a new mock instance.
func NewMockAuditPublisher(ctrl *gomock.Controller) *MockAuditPublisher {
	mock := &MockAuditPublisher{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisher) EXPECT() *MockAuditPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAuditPublisher) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAuditPublisherMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAuditPublisher)(nil).Close), ctx)
}

// Publish mocks base method.
func (m *MockAuditPublisher) Publish(e dto.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", e)
}

// Publish indicates an expected call of Publish.
func (mr *MockAuditPublisherMockRecorder) Publish(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAuditPublisher)(nil).Publish), e)
}

// Subscribe mocks base method.
func (m *MockAuditPublisher) Subscribe(subscriberID string) (<-chan dto.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", subscriberID)
	ret0, _ := ret[0].(<-chan dto.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockAuditPublisherMockRecorder) Subscribe(subscriberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAuditPublisher)(nil).Subscribe), subscriberID)
}

// Unsubscribe mocks base method.
func (m *MockAuditPublisher) Unsubscribe(subscriberID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", subscriberID)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockAuditPublisherMockRecorder) Unsubscribe(subscriberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAuditPublisher)(nil).Unsubscribe), subscriberID)
}
